 version: 1
 labels:
- label: "enhancement"
  title: "^feat.*/i"
- label: "bug"
  title: "^fix.*/i"
- label: "chore"
  title: "^chore.*/i"
  title: "^build.*/i"
  title: "^style.*/i"
- label: "docs"
  title: "^docs.*/i"
- label: "testing"
  title: "^test.*/i"
- label: "refactor"
  title: "^refactor.*/i"