 version: 1
 labels:
- label: "enhancement"
  title: "^feat.*"
- label: "bug"
  title: "^fix.*"
- label: "chore"
  title: "^chore.*"
  title: "^build.*"
  title: "^style.*"
- label: "docs"
  title: "^docs.*"
- label: "testing"
  title: "^test.*"
- label: "refactor"
  title: "^refactor.*"