 version: 1
 labels:
  - label: "enhancement"
    title: "^[fF][eE][aA][tT].*"
  - label: "bug"
    title: "^fix.*"
  - label: "chore"
    title: "^chore.*"
  - label: "chore"
    title: "^build.*"
  - label: "docs"
    title: "^docs.*"
  - label: "testing"
    title: "^test.*"
  - label: "refactor"
    title: "^refactor.*"