labelToAdd: 'need more info'
labelsToCheck:
  - bug
commentHeader: 'More information is required to proceed with this issue:'
requiredItems:
  -
    response: '- Use the issue template for bugs'
    requireAll: true
    content:
      - '## Actual Behavior'
      - '## Expected Behavior'
  -
    response: '- A sample that reproduces the issue'
    requireAll: false
    content:
      - jsbin.com
      - codepen.io
      - jsfiddle.net
      - codesandbox.io
commentFooter: 'This issue will be automatically closed in a day if the information is not provided. Thanks for your understanding.'
