labelToAdd: 'need more info'
labelsToCheck:
  - bug
commentHeader: 'More information is required to proceed with this issue:'
requiredItems:
  -
    response: '- Use the [issue template](https://github.com/Esri/calcite-components/issues/new?assignees=&labels=bug%2C+0+-+new%2C+needs+triage&template=bug.md&title=Bug%3A+) for bugs'
    requireAll: true
    content:
      - '## Actual Behavior'
      - '## Expected Behavior'
  -
    response: '- A [codepen](codepen.io), [codesandbox](codesandbox.io], or [jsbin](jsbin.com) that reproduces the issue'
    requireAll: false
    content:
      - jsbin.com
      - codepen.io
      - codesandbox.io
commentFooter: 'This issue will be automatically closed in a day if the information is not provided. Thanks for your understanding.'
