# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json
name: Question
description: Ask for help - not a code change.
labels: ["question"]
assignees:
  - benelan
body:
  - type: markdown
    attributes:
      value: |
        Thanks for logging an issue, I appreciate the feedback! Please confirm the following before continuing:
        - You are using the latest version, since the issue may already be fixed.
        - There are no [existing issues](/../../issues?q=is%3Aopen+is%3Aissue+label%3Aquestion) with the same question.
            - If there is a duplicate issue, please add a 👍 reaction instead of creating a new one.
  - type: textarea
    id: question
    attributes:
      label: Question
      description: How can I help?
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Helpful Details
      description: Context, topic, examples, etc.
    validations:
      required: false
