name: Add Esri Product Label
on:
  issues:
    types: [opened, edited]
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        with:
          script: |

            const { data: issue } = await github.issues.get({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const { ISSUE_BODY } = process.env;
            if (!ISSUE_BODY) {
              throw new Error("Could not determine the issue body")
            }
            console.log("ISSUE_BODY:", ISSUE_BODY);
            console.log("github.event.issue.body:", github.event.issue.body);
            console.log("context.issue.body:", context.issue.body);
            console.log("issue.body:", issue.body)

            const productRegexMatch = ISSUE_BODY.match(/(?<=### Esri team\n\n).*/);

            if (!productRegexMatch) {
              throw new Error("Could not determine the product")
            }

            const getLabel = (product) => {
              switch (product) {
                case "ArcGIS Map Viewer":
                  return "MV";
                case "ArcGIS API for JavaScript":
                  return "JSAPI";
                case "ArcGIS Hub":
                  return "Hub";
                case "ArcGIS Dashboard":
                  return "Dashboard";
                default:
                  return "";
              }
            };

            const label = getLabel(productRegexMatch[0]);

            if (label) {
              await github.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: [label],
              });
            }
