name: Add Esri Product Label
on:
  issues:
    types: [opened, edited]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const {
              repo: { owner, repo },
              payload: {
                issue: { body, labels: currentLabels, number: issue_number },
              },
            } = context;

            if (!body) {
              console.log("could not determine the issue body");
              return;
            }

            const productRegex = new RegExp("(?<=### Esri team[\r\n|\r|\n]{2})S.+$", "m");
            // the way GitHub parses the issue body into plaintext requires this exact format
            const productEditRegex = new RegExp("(?<=### Esri team\r\n\r\n).+", "m");

            const productCreateRegexMatch = body.match(productRegex);
            const productEditRegexMatch = body.match(productEditRegex);

            const product = (
              productCreateRegexMatch && productCreateRegexMatch[0]
                ? productCreateRegexMatch[0]
                : productEditRegexMatch && productEditRegexMatch[0]
                ? productEditRegexMatch[0]
                : ""
            ).trim();

            if (product && product !== "N/A") {
              /** Creates a label if it does not exist */
              try {
                await github.rest.issues.getLabel({
                  owner,
                  repo,
                  name: product,
                });
              } catch (e) {
                await github.rest.issues.createLabel({
                  owner,
                  repo,
                  name: product,
                  color: "006B75",
                  description: `Issues logged by ${product} team members.`,
                });
              }

              /** remove any existing product label(s) */
              const labels = currentLabels
                .filter((l) => !/Issues logged by/.test(l.description))
                .map((l) => l.name);

              labels.push(product);

              await github.rest.issues.setLabels({
                issue_number,
                owner,
                repo,
                labels,
              });
            }
