name: Add current milestone
on:
  issues:
    types: [opened, edited]
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  add:
    if: github.event.pull_request.merged == true || github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - uses: benelan/milestone-action@main
