name: Add current milestone
on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  add:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: benelan/milestone-action@v1.2.0
