name: Analyze Sample Builds
on:
  pull_request:
    branches: [master]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: check for package changes
        id: build
        run: |
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          # list of all package.json files changed
          packages_changed=$(git diff --name-only "$current_branch" $(git merge-base "$current_branch" origin/master) --)
          echo "package.json files changed: $packages_changed"
          # skip if no packages are changed
          if [ -z "$packages_changed" ]; then
            echo "no package.json files changed, skipping build analysis"
          else
            echo "analyzing builds"
            echo "::set-output name=skip::false"
          fi
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - if: steps.build.outputs.skip == 'false'
        run: node ./.github/scripts/analyze-builds.js
      - name: create pull request
        if: steps.build.outputs.skip == 'false'
        uses: peter-evans/create-pull-request@v3
        with:
          base: master
          branch: build-analysis
          commit-message: "ci: analyze esm sample builds"
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "ci: analyze esm sample builds"
          body: This PR was automatically generated by the build-analysis GitHub Action
