name: "Assign for Verification"
on:
  issues:
    types: [labeled]
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
    - uses: kyanagimoto/assignee4label@v1.1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: '.github/verify.yml'
