name: Verify Install
on:
  issues:
    types: [labeled]
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
           const { label, sender, issue, repo } = context.payload;
            if (label && label.name === "3 - installed") {
              const assignees =
                sender && sender.login === "benelan"
                  ? ["jcfranco", "julio8a"]
                  : ["benelan"];
              await github.issues.createComment({
                issue_number: issue.number,
                owner: repo.owner,
                repo: repo.repo,
                body: "Installed, assigning for verification.",
              });
              await github.issues.update({
                issue_number: issue.number,
                owner: repo.owner,
                repo: repo.repo,
                assignees,
              });
            }
