name: Verify Install
on:
  issues:
    types: [labeled]
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            const {label, sender, issue} = context.payload
            if (label && label.name === "3 - installed" && sender && sender.login !== "benelan") {
              github.issues.createComment({
                issue_number: issue.number,
                owner: issue.owner,
                repo: issue.repo,
                body: "This issue is installed, assigning @benelan for verification",
              });
              await github.issues.update({
                issue_number: issue.number,
                owner: issue.owner,
                repo: issue.repo,
                assignees: ["benelan"]
              });
            }
