name: Verify Install
on:
  issues:
    types: [labeled]
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            const {label, sender} = context.payload
            if (sender && sender.login === "benelan") {
              console.log("Ben doesn't verify his own issues, ending run")
              return
            }
            if (label && label.name === "3 - installed") {
              github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "This issue is installed, assigning @benelan for verification",
              });
              await github.issues.update({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                assignees: ["benelan"]
              });
            }
