name: Create Check
on:
  # pull_request:
  #   branches: [main]
  # # need to run on the base branch when merging to keep the baseline state up to date
  # push:
  #   branches: [main]
  workflow_dispatch:
jobs:
  screener:
    if: "github.event_name != 'workflow_dispatch'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: skip for markdown only
        id: one
        run: |
          git fetch --deepen=100
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          echo "branch: $current_branch"
          if [ "$current_branch" == "main" ]; then
            # diff of last commit excluding md (assumes squash merge)
            screenable_changes=$(git diff --name-only @~..@ -- . ':(exclude)*.md')
            echo "push run"
          else
            # diff of branch excluding md
            screenable_changes=$(git diff --name-only "$current_branch" $(git merge-base "$current_branch" origin/main) -- . ':(exclude)*.md')
            echo "pr run"
          fi
          echo "changed files: $screenable_changes"
          # skip if there are only md changes
          if [ -z "$screenable_changes" ]; then
            echo "skip screener"
            echo "::set-output name=skip::true"
          else
            echo "skip screener"
            echo "::set-output name=skip::false"
          fi
      - if: steps.one.outputs.skip == 'true'
        name: skip screener
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: screener
          description: Skip Screener
          state:  success
          sha: ${{github.event.pull_request.head.sha || github.sha}}
      - if: steps.one.outputs.skip == 'false'
        name: run screener
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: screener
          description: Run Screener
          state:  success
          sha: ${{github.event.pull_request.head.sha || github.sha}}
  manual_test:
    if: "github.event_name == 'workflow_dispatch'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: lts/*
      - run: npm ci --legacy-peer-deps
      - name: run screener check
        run: echo "testing 123"
