name: Screener # test
on: [pull_request_target]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: report
        id: report
        run: echo "::notice::<a href='https://screener.io/v2'>Screener Report</a>"