name: Screener # test
on: [pull_request_target]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: report
        id: report
        run:
          echo "::set-output name=report::https://screener.io/v2"
      - uses: actions/checkout@v2
      - name: set status
        if: always()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: Screener Report
          description: Click details to view the report on Screener
          state:  ${{ job.status }}
          sha: ${{github.event.pull_request.head.sha || github.sha}}
          target_url: ${{ steps.report.outputs.report }}