name: Screener #test
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: skip for markdown only
        run: |
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          if [ ! git diff --name-only $current_branch $(git merge-base $current_branch master) -- . ':(exclude)*.md']; then;
            exit 0
          fi
      - name: report
        id: report
        run:
          echo "::set-output name=report::https://screener.io/v2"
      - name: set status
        if: always()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.ADMIN_TOKEN}}
          context: Screener Report
          description: Click details to view the report on Screener
          state:  ${{ job.status }}
          sha: ${{github.event.pull_request.head.sha || github.sha}}
          target_url: ${{ steps.report.outputs.report }}
