name: Screener Check
on:
  pull_request:
    branches: [master]
  # need to run on the base branch when merging to keep the baseline state up to date
  push:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: skip for markdown only
        id: one
        run: |
          git fetch --deepen=100
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          echo "$current_branch"
          if [ "$current_branch" == "master" ]; then
            # diff of last commit excluding md (assumes squash merge)
            screenable_changes=$(git diff --name-only @~..@ -- . ':(exclude)*.md')
            echo "on master for pushes"
          else
            # diff of branch excluding md
            screenable_changes=$(git diff --name-only "$current_branch" $(git merge-base "$current_branch" origin/master) -- . ':(exclude)*.md')
            echo "on branch for prs"
          fi
          echo "$screenable_changes"
          # skip if there are only md changes
          if [ -z "$screenable_changes" ]; then
            echo "skip screener"
            echo "::set-output name=skip::skip"
          else
            echo "run screener"
            echo "::set-output name=skip::screen"
          fi
      - if: steps.one.outputs.skip == 'skip'
        name: skip screener
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.ADMIN_TOKEN}}
          context: screener
          description: Skip Screener
          state:  success
          sha: ${{github.event.pull_request.head.sha || github.sha}}
      - if: steps.one.outputs.skip == 'screen'
        name: run screener
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.ADMIN_TOKEN}}
          context: screener
          description: Run Screener
          state:  success
          sha: ${{github.event.pull_request.head.sha || github.sha}}