name: Screener Check
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: skip for markdown only
        id: skip
        run: |
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          screenable_files=$(git diff --name-only "$current_branch" $(git merge-base "$current_branch" origin/master) -- . ':(exclude)*.yml')
          if [ $screenable_files ]; then
            exit 0
          else
            exit 1
          fi
      - name: run screener
        if: steps.skip.conclusion == 'success'
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.ADMIN_TOKEN}}
          context: screener
          description: Run screener
          state:  success
          sha: ${{github.event.pull_request.head.sha || github.sha}}

      - name: set skip status
        if: steps.skip.conclusion == 'failure'
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.ADMIN_TOKEN}}
          context: screener
          description: Screener report skipped
          state:  success
          sha: ${{github.event.pull_request.head.sha || github.sha}}
      -