name: Screener Check
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: skip for markdown only
        id: skip
        run: |
          git fetch --deepen=100
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          screenable_changes=$(git diff --name-only "$current_branch" $(git merge-base "$current_branch" origin/master) -- . ':(exclude)*.md')
          if [ -z "$screenable_changes" ]; then
            echo "::set-output name=skip::true"
          else
            echo "::set-output name=skip::false"
          fi
      - name: run screener
        if: ${{ steps.skip.outputs.skip }} == false
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.ADMIN_TOKEN}}
          context: screener
          description: Run screener
          state:  success
          sha: ${{github.event.pull_request.head.sha || github.sha}}
      - name: set skip status
        if: ${{ steps.skip.outputs.skip }} == true
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.ADMIN_TOKEN}}
          context: screener
          description: Screener report skipped
          state:  success
          sha: ${{github.event.pull_request.head.sha || github.sha}}