name: Deploy Next
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ secrets.PRIMARY_CONTACT }} == "benelan"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
        env:
           PRIMARY_CONTACT: ${{ secrets.PRIMARY_CONTACT }}
        if: ${{ env.PRIMARY_CONTACT }} == "benelan"
      - run: npm install
      - run: bash testScript.sh
