name: Limit Pull Requests For Maintenance Releases
on:
  pull_request:
    branches: [main]
    types: [labeled, synchronize]
jobs:
  move:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/limitPullRequestsForMaintenanceReleases.js')
            await action({github, context, core})
