name: PR Bot
on:
  pull_request:
    branches: [master]
jobs:
  milestone:
    runs-on: ubuntu-latest
    steps:
      - uses: benelan/milestone-action@v1.1.0
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const {
              repo: { owner, repo, number: issue_number },
              payload: { issue, pull_request }
            } = context;

            const conventionalCommitRegex =
              /^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([\w ,-]+\))?(!?:\s+)([\w ]+[\s\S]*)/i;

            const commitMessage = (issue && issue.title) || (pull_request && pull_request.title);
            if (!commitMessage) {
              console.log("No title found, ending run.");
              return;
            }

            const match = commitMessage.match(conventionalCommitRegex);
            if (match && match.length > 1) {
              const labels = [getLabelName(match[1])];
              await github.issues.addLabels({
                owner,
                repo,
                issue_number,
                labels
              });

              function getLabelName(type) {
                switch (type) {
                  case "feat":
                    return "enhancement";
                  case "fix":
                    return "bug";
                  case "docs":
                    return "docs";
                  case "test":
                    return "testing";
                  case "refactor":
                    return "refactor";
                  case "tooling":
                    return "tooling";
                  default:
                    return "chore";
                }
              }
            }