name: Auto Merge
on: issue_comment
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
           chmod +x auto-merge.sh
           ./auto-merge.sh
        shell: bash
