name: Auto Merge
on: issue_comment
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo actor --- ${{ github.actor }}
      - run: echo pr ---  ${{ github.event.pull_request.user.login }}
      - run: echo issue ---  ${{ github.event.issue.user.login }}
      - name: merge
        if: ${{ github.event.issue_comment.issue.user.login }} == ${{ github.actor }}
        uses: Goobles/gh-actions-merge-command@v1
        with:
          allow_ff: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
