name: Shell CI
on:
  push:
    branches: [main]
permissions:
  contents: write
  pull-requests: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "2.17.1"
      - uses: mfinelli/setup-shfmt@v3
      - run: make format
      - uses: actionsx/prettier@v2
        with:
          args: --fix docs/*.md
      - uses: DavidAnson/markdownlint-cli2-action@v14
        with:
          fix: true
          config: .markdownlint.json
          globs: "docs/*.md"
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: generate man page and format code"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

  release:
    name: release
    runs-on: ubuntu-latest
    needs: format
    steps:
      - uses: google-github-actions/release-please-action@v3.7.9
        id: release
        with:
          release-type: simple
          package-name: git-mux
          token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: main
          extra-files: bin/git-mux
          plugins: sentence-case
          prerelease: true
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
      - name: tag stable versions
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git tag -d stable || true
          git push origin :stable || true
          git tag -a stable -m "Current Stable Release"
          git push origin stable
