name: Release Notification
on:
  release:
    types: [published]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get release version
        uses: actions/github-script@v4
        with:
          script: |
            const release = context.payload.release
            if (!release) {
              console.log('No release found')
              return
            }
            console.log('release.tag_name')
            core.exportVariable('RELEASE_VERSION', release.tag_name);
      - name: Message CC Teams Channel 
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.TEAMS_WEBHOOK_URI }}
          title: Test
          summary: Test
          text: "@General <code>@esri/calcite-components@${{ env.RELEASE_VERSION }}</code> released! 🚀 Check out the [changelog](https://github.com/Esri/calcite-components/blob/master/CHANGELOG.md) for more info."