name: Release Notification
on:
  release:
    types: [released]
jobs:
  notify:
    if: ${{ context.payload.tag_name }}
    runs-on: ubuntu-latest
    steps:
      #- run: sleep 30m # wait 30min for npm release
      #  shell: bash
      - uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.TEAMS_WEBHOOK_URI }}
          title: ${{ context.payload.tag_name }}
          summary: ${{ context.payload.tag_name }}
          text: "🚀 <code>@esri/calcite-components@${{ context.payload.tag_name }}</code> released! Check out the [changelog](https://github.com/Esri/calcite-components/blob/master/CHANGELOG.md) for more info. 🚀"