name: Release Notification
on:
  workflow_dispatch:
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        env:
          release_tag_name: 123.456
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"@context": "http://schema.org/extensions", "@type": "MessageCard", "title": ${{ env.release_tag_name }}, "text": "🚀 <code>@esri/calcite-components@${{ env.release_tag_name }}</code> released! Check out the [changelog](https://github.com/Esri/calcite-components/blob/master/CHANGELOG.md#changelog) for more info. 🚀"}' ${{ secrets.TEAMS_WEBHOOK_URI_RELEASE }}