name: 'Issue Info'
on:
  issues:
    types: [labeled]
    branches: [master]
  issue_comment:
    types: [created]
    branches: [master]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: benelan/need-info-action@main
        with:
         repo-token: ${{ secrets.GITHUB_TOKEN }}
